name: bopmaps
description: A musical geocaching app that allows users to drop music pins at physical locations.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  http: ^1.3.0
  shared_preferences: ^2.1.1
  flutter_dotenv: ^5.0.2
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  firebase_storage: ^11.2.1
  cloud_firestore: ^4.7.1
  firebase_messaging: ^14.6.1
  firebase_analytics: ^10.4.1
  google_sign_in: ^6.1.0
  flutter_secure_storage: ^8.0.0
  # Commenting out mapbox_gl temporarily since it causes dependency conflicts
  # mapbox_gl: ^0.16.0 
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  url_launcher: ^6.1.11
  image_picker: ^0.8.7+5
  path_provider: ^2.0.15
  intl: ^0.18.1
  uuid: ^3.0.7
  flutter_svg: ^2.0.5
  audio_service: ^0.18.9
  just_audio: ^0.9.33
  rxdart: ^0.27.7
  carousel_slider: ^4.2.1
  flutter_local_notifications: ^14.1.0
  connectivity_plus: ^4.0.1
  permission_handler: ^10.2.0
  package_info_plus: ^4.0.1
  share_plus: ^7.0.1
  lottie: ^2.3.2
  flutter_web_auth: ^0.5.0
  # Added for modern 2.5D map implementation
  flutter_map: ^6.0.1
  latlong2: ^0.9.0
  vector_math: ^2.1.4
  flutter_map_marker_cluster: ^1.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.4
  # Commenting out flutter_launcher_icons temporarily since it causes dependency conflicts
  # flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env  # Uncommented since we've created this file
    # Add other assets here

  # Uncommented font references since we've added the font files
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700 